# Generated by Django 2.2.11 on 2020-09-02 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=30, verbose_name='CPF ou CNPJ')),
                ('cep', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=120)),
                ('numero', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcionario', models.CharField(max_length=100, verbose_name='Nome Funcionário')),
                ('setor_funcionario', models.CharField(max_length=40, verbose_name='Setor do Funcionário')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('descricao', models.CharField(max_length=120, verbose_name='Descrição')),
                ('estoque_max', models.IntegerField(max_length=8, verbose_name='Estoque Máximo')),
                ('estoque_min', models.IntegerField(max_length=8, verbose_name='Estoque Mínimo')),
                ('codigo_barras', models.CharField(max_length=30, verbose_name='Código de Barras')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Categoria')),
                ('unidademedida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.UnidadeMedida')),
            ],
        ),
    ]
