# Generated by Django 2.2.11 on 2020-10-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='documento',
            field=models.CharField(max_length=30, unique=True, verbose_name='CPF ou CNPJ'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_max',
            field=models.IntegerField(verbose_name='Estoque Máximo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_min',
            field=models.IntegerField(verbose_name='Estoque Mínimo'),
        ),
    ]
